export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERT_CREATE = 'ADVERT_CREATE';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_SEARCH = 'GET_SEARCH';
export const SEARCH_ADVERTS = 'SEARCH_ADVERTS';
